/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"

#define LEDDELAY    1000000

void delay(volatile uint32_t);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "display7segmentmax7219.h"

Display7SegmentMax7219 display;
int i = 1;
extern "C" void TIM2_IRQHandler(void)
{
	if(TIM2->SR & TIM_SR_UIF)           // Проверяем, что это нас именно переполнение вызывало. Т.к. у таймера несколько видов событий и переполнение одно из
	{
		TIM2->SR = ~TIM_SR_UIF;        //сбросить флаг. Да тут, в отличии от AVR это надо делать вручную.

		// Тут делаем свои дела
		display.displayInt64Number(i++, false);
		//GPIOA->ODR ^= (1U << 5);  // Toggle LED
	}

}

int main(void)
{
	display.shutDownOn();
	display.clear(8);
	display.setVisibleDigits(3);
	display.setNoDecodeAllDigits();

	__enable_irq();
	//SystemInit();
	/* Each module is powered separately. In order to turn on a module
	 * its relevant clock needs to be enabled first.
	 * The clock enables are located at RCC module in the relevant bus registers
	 * STM32F4-Discovery board LEDs are connected to GPIOD pins 12, 13, 14, 15.
	 * All the GPIO are connected to AHB1 bus, so the relevant register for the
	 * clocks is AHB1ENR.
	 * More info in Chapter 7 - RCC in RM0090
	 */

	/* Enable GPIOD clock (AHB1ENR: bit 3) */
	// AHB1ENR: XXXX XXXX XXXX XXXX XXXX XXXX XXXX 1XXX
	//RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	// Note: |= means read the contents of the left operand, or it with
	//   the right operand and write the result back to the left operand

	// Another way to write a 1 to a bit location is to shift it that much
	// Meaning shift number 1, 3 times to the left. Which would result in
	// 0b1000 or 0x8
	// RCC->AHB1ENR |= (1U << 3);

	// We can also use the predefined directives from stm header to do the same thing.
	// RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	// RCC_AHB1ENR_GPIODEN here will expand to (1 << 3)

	/* Make Pin 12 output (MODER: bits 25:24) */
	// Each pin is represented with two bits on the MODER register
	// 00 - input (reset state)
	// 01 - output
	// 10 - alternate function
	// 11 - analog mode

	// We can leave the pin at default value to make it an input pin.
	// In order to make a pin output, we need to write 01 to the relevant
	// section in MODER register
	// We first need to AND it to reset them, then OR it to set them.
	//                     bit31                                         bit0
	// MODER register bits : xx xx xx 01 XX XX XX XX XX XX XX XX XX XX XX XX
	//                      p15      p12                                  p0

	//GPIOA->MODER &= 0xFCFFFFFF;   // Reset bits 25:24 to clear old values
	//GPIOA->MODER |= 0x01000000;   // Set MODER bits 25:24 to 01

	// We could also use a more systematic approach by shifting to bits
	// GPIOD->MODER &= ~(3U << 24);
	// GPIOD->MODER |=  (1U << 24);

	// Since each pin is represented with two bits, we needed to shift 24 times
	// to write to the bits related to pin 12 (times 2). We could change our code to
	// auto-calculate the relevant bit location.
	// GPIOD->MODER &= ~(3U << 2*12);
	// GPIOD->MODER |=  (1U << 2*12);

	// As a side note:
	// First AND operations to clear the bits is not really important for first
	// boot up setup, but if we ever want to change the pin behavior in the middle
	// of the code, we need to make sure it is cleared before writing it.

	/* We do not need to change the speed of the pins, leave them floating
	 * and leave them as push-pull, so no need to touch OTYPER, OSPEEDR, and OPUPDR
	 * However, if we want to use a open-drain required protocol (i.e. I2C), we need
	 * to declare the pin as open-drain from OTYPER register
	 */

	/* Set or clear pins (ODR: bit 12) */
	// Set pin 12 to 1 to turn on an LED
	// ODR: xxx1 XXXX XXXX XXXX
	//GPIOA->ODR |= 0x1000;
	//GPIOA->MODER &= ~GPIO_MODER_MODER0; 	 /* reset a PORTA for input*/
	//GPIOA->MODER |= GPIO_MODER_MODER5_0;  /* Set up port A pin 5 as output*/

	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;    	// Подаем тактирование на таймер от шины APB1
	TIM2->PSC = 7;				// Частота этой шины 36 мегагерц. Так что в предделитель записываем 36-1, получим 1МГц
	TIM2->ARR = (128000-1);				// Потолком счета таймера укажем 100-1. Получим деление на 100 в частоте вызова прерываний.


	TIM2->CR1 |= TIM_CR1_ARPE | TIM_CR1_URS | TIM_CR1_CEN;  		//  ARPE=1 - буфферизируем регистр предзагрузки таймера опциональная вещь.
	// URS=1	- разрешаем из событий таймера только события от переполнения
	// CEN=1 - запускаем таймер
	TIM2->DIER  |= TIM_DIER_UIE;					// UIE=1 - Разрешаем прерывание от переполнения

	NVIC_SetPriority(TIM2_IRQn,14);				// Очень важный момент!!! Надо правильно выставить приоритеты. Они должны быть в диапазоне между
	// configKERNEL_INTERRUPT_PRIORITY  и configMAX_SYSCALL_INTERRUPT_PRIORITY
	NVIC_EnableIRQ(TIM2_IRQn);
	// With shifting
	// GPIOD->ODR |= (1U << 12);

	// the code should never leave its master loop, hence while(1) or for(;;)
	while(1)
	{
		//		delay(LEDDELAY);
		//		GPIOA->ODR ^= (1U << 5);  // Toggle LED
	}
}

void delay(volatile uint32_t s)
{
	for(; s>0; s--);
}
