#include "stm32f4xx.h"
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(unsigned dly)
{
    while(dly--);
}

int main(void)
{
	 // Turn on GPIOB
	    RCC_AHB2ENR |= BIT1;
	    GPIOB_MODER |= BIT6;
	    GPIOB_MODER &= ~BIT7;
	        while(1)
	    {
	        GPIOB_ODR |= BIT3;  // Turn on green led
	        delay(100000);
	        GPIOB_ODR &= ~BIT3; // Turn off green led
	        delay(100000);
	    }
}
